# Generated by Django 3.2 on 2022-02-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_ventas_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad_vendida',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
