# Generated by Django 3.2 on 2022-02-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=50)),
                ('tipo_bebida', models.CharField(max_length=50)),
                ('id_interno', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('cantidad_stock', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
